Hw3
RobertGabdullin/java-course-2024-backend pull request #3
Opened 2024-03-03 17:36 UTC by RobertGabdullin

2024-03-10 16:06 UTC, edikgoose requested changes
Много замечаний, поправь все и обязательно отправь новую версию
Если не буду игнорить больше двух дней, пиши в тг @edikgoose

В целом все ок, задание сделано.

2024-03-10 16:06 UTC, edikgoose commented on scrapper/src/main/java/edu/java/service/StackOverflowClient.java
> +        this.webClient = webClientBuilder.baseUrl(applicationConfig.stackOverflowBaseUrl()).build();
Почему-то не заметил в прошлом дз. Лучше передавать base-url строкой и не передавать ApplicationConfig файл.

2024-03-10 16:06 UTC, edikgoose commented on scrapper/src/main/java/edu/java/scrapper_client/ScrapperClient.java
> +public class ScrapperClient {
А почему у тебя ScrapperClient внутри самого скраппера?

2024-03-10 16:06 UTC, edikgoose commented on scrapper/src/main/java/edu/java/scrapper_client/ScrapperClient.java
> +package edu.java.scrapper_client;
Пакеты не называют через нижнее подчеркивание (хотя вроде по стандарту допускается).
Лучше сделать пакет client и внутри него сделать пакеты scrapper, github, stackoverflow

2024-03-10 16:06 UTC, edikgoose commented on scrapper/src/main/java/edu/java/controller/ApiController.java
> +public class ApiController {
Лучше называй контроллер, соответствующе его домену. То есть, например, ChatController, LinkController.
Если получается так, что класс отвечает за несколько доменов, то его пора распиливать

2024-03-10 16:06 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/controller/request/UpdateRequest.java
> +package edu.java.bot.controller.request;
Для моделек обычно создается отдельный пакет dto. Он не вкладывается в controller пакет. В controller пакете лежат только контроллеры (это же касается exception'ов)

2024-03-10 16:06 UTC, edikgoose commented on scrapper/src/main/java/edu/java/bot_client/BotClient.java
> +        this.webClient = webClientBuilder.baseUrl("http://localhost:8080").build();
Урл не должен указываться в коде. Все значения должны браться из application.yaml файла через ConfigurationProperties механизм спринга

2024-03-10 16:06 UTC, edikgoose commented on scrapper/src/main/java/edu/java/configuration/SchedulerConfig.java
> +    public ApplicationConfig.Scheduler scheduler() {
Намного проще просто в ApplicationConfig файле навесить @Bean аннотацию на record Scheduler)

2024-03-10 16:06 UTC, edikgoose commented on scrapper/src/main/java/edu/java/data_transfer/GitHubActivity.java
> +package edu.java.data_transfer;
проще dto)

2024-03-16 15:13 UTC, RobertGabdullin commented
@edikgoose Спасибо за ревью. Я исправил все, кроме Bean с scheduler'ом. Я не очень понимаю, куда его навесить :(
Еще было бы классно проверить с baseUrl. Я кажется не до конца понимаю, что требуется.

2024-03-27 22:08 UTC, merged