Hw4
RobertGabdullin/java-course-2024-backend pull request #4
Opened 2024-03-16 22:40 UTC by RobertGabdullin

2024-03-18 16:40 UTC, edikgoose requested changes
Хорошо сделал, но нет запуска миграций при тесте, поэтому -3 балла
И заливай, пожалуйста, в мре только те изменения, которые касаются текущего дз. А то сложно найти, что сделано в рамках текущего дз, а что в рамках прошлых

2024-03-18 16:40 UTC, edikgoose commented on scrapper/src/main/resources/migrations/V1__Create_Chat_Table.sql
> +CREATE TABLE Chat (
Лучше добавлять if not exist, чтобы он не пытался создать таблицу, если она уже есть

2024-03-18 16:40 UTC, edikgoose commented on scrapper/src/main/resources/migrations/V1__Create_Chat_Table.sql
> +    first_name      VARCHAR(255),
Обычно TEXT используют

2024-03-18 16:40 UTC, edikgoose commented on scrapper/src/main/resources/migrations/V2__Create_Link_Table.sql
> +    FOREIGN KEY (chat_id) REFERENCES Chat(chat_id),
Отношение по задание "многие ко многим", поэтому тебе нужна промежуточная таблица, которая хранит связку chat-link. Это нужно, чтобы не повторять одни и те же ссылки. Например, в твоем случае, если в разные 50 чатов сохранится одна ссылка, будет добавлено 50 ссылок в таблицу, что не эффективно по памяти.

2024-04-30 20:28 UTC, Vladislav-Kisliy approved these changes
оставил мелкий комментарий, в целом отлично

2024-04-30 20:28 UTC, Vladislav-Kisliy commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            e.printStackTrace();
очень не рекомендуется использовать этот метод, почти всегда лучше использовать логгер

2024-05-04 20:16 UTC, merged